### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by BeerTai** [neulab/SpanNER#1]
您好，我在运行的时候出现如下的错误：
Traceback (most recent call last):
  File "trainer.py", line 598, in <module>
    main()
  File "trainer.py", line 592, in main
    trainer.fit(model)
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1030, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1114, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 118, in run
    output = self.on_run_end()
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 132, in on_run_end
    self.evaluation_epoch_end(outputs)
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 242, in evaluation_epoch_end
    model.validation_epoch_end(outputs)
  File "trainer.py", line 342, in validation_epoch_end
    correct_pred, total_pred, total_golden = all_counts
  File "/home/sdd/jsun/anaconda3/envs/py38/lib/python3.8/site-packages/torch/tensor.py", line 450, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
我的pytorch-lightning的版本是最新版本，对pytorch-lightning不太熟悉，请问该如何解决？谢谢您

**Comment by BeerTai** [comment]
换成0.9版本就好了。
