### ISSUE TITLE
cuda error问题

### ISSUE THREAD

**Issue by WalkerJYT** [neulab/SpanNER#2]
好的，谢谢老师指导

**Comment by jinlanfu** [comment]
If there is no error in the data entered, likely, the package has not been installed correctly. You can try to run this model on the CPU. Running on the CPU will give much more detailed errors.

**Comment by WalkerJYT** [comment]
您好，我的模型下载的是
bert_config_dir='uncased_L-12_H-768_A-12'
其他的package都是根据提示直接下载的，数据集也是您代码自带的coll03，然后是在运行一部分之后显示
![image](https://user-images.githubusercontent.com/93082012/145319033-4e1e667f-7dfd-40b0-8fb5-a7feab7043fa.png)
然后下面显示的错误是：
Traceback (most recent call last):
  File "trainer.py", line 600, in <module>
    main()
  File "trainer.py", line 594, in main
    trainer.fit(model)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1064, in fit
    results = self.accelerator_backend.train()
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/accelerators/dp_backend.py", line 97, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 1012, in optimizer_closure
    opt_idx, hiddens)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 1197, in training_forward
    output = self.model(*args)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 76, in forward
    return self.module.training_step(*inputs[0], **kwargs[0])
  File "trainer.py", line 252, in training_step
    all_span_rep = self.forward(loadall,all_span_lens,all_span_idxs_ltoken,tokens, attention_mask, token_type_ids)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 135, in decorate_autocast
    return func(*args, **kwargs)
  File "trainer.py", line 198, in forward
    return self.model(loadall,all_span_lens,all_span_idxs_ltoken,input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/SpanNER-main/models/bert_model_spanner.py", line 92, in forward
    bert_outputs = self.bert(input_ids, token_type_ids=token_type_ids, attention_mask=attention_mask)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 1006, in forward
    return_dict=return_dict,
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 590, in forward
    output_attentions,
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 512, in forward
    self.feed_forward_chunk, self.chunk_size_feed_forward, self.seq_len_dim, attention_output
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2360, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 524, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 437, in forward
    hidden_states = self.dense(hidden_states)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/nn/functional.py", line 1678, in linear
    output += bias
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1595629403081/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7fca7211377d in /home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xb5d (0x7fca72363d9d in /home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fca720ffb1d in /home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x53f0ea (0x7fcaab9960ea in /home1/ytjia/anaconda3/envs/torch16/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xe7 (0x7fcac6253bf7 in /lib/x86_64-linux-gnu/libc.so.6)
会不会是我模型下载错误了，或者是代码可能有点问题呢

**Comment by WalkerJYT** [comment]
教授方便将这个模型的一些具体的相关配置发给我吗？我想再重新下载代码和模型搭建一下
